# Generated by Django 5.2.6 on 2025-12-09 15:57

import django.db.models.deletion
import keys.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activationlog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Лог активации', 'verbose_name_plural': 'Логи активаций'},
        ),
        migrations.AlterModelOptions(
            name='licensekey',
            options={'ordering': ['-created_at'], 'verbose_name': 'Лицензия', 'verbose_name_plural': 'Лицензии'},
        ),
        migrations.AlterField(
            model_name='activationlog',
            name='ip_address',
            field=models.GenericIPAddressField(verbose_name='IP Адрес'),
        ),
        migrations.AlterField(
            model_name='activationlog',
            name='key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='keys.licensekey', verbose_name='Ключ'),
        ),
        migrations.AlterField(
            model_name='activationlog',
            name='success',
            field=models.BooleanField(verbose_name='Успешно'),
        ),
        migrations.AlterField(
            model_name='activationlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время запроса'),
        ),
        migrations.AlterField(
            model_name='licensekey',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='licensekey',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='licensekey',
            name='key',
            field=models.CharField(default=keys.models.generate_uuid_hex, max_length=32, unique=True, verbose_name='Лицензионный ключ'),
        ),
        migrations.AlterField(
            model_name='licensekey',
            name='last_used',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последнее использование'),
        ),
        migrations.AlterField(
            model_name='licensekey',
            name='steam_id',
            field=models.CharField(help_text='Уникальный идентификатор Steam аккаунта', max_length=20, unique=True, verbose_name='Steam ID (64)'),
        ),
    ]
